---
# handlers file for lamp
- name: Restart Apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted

- name: Restart MySQL
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: restarted
